import React, { useEffect, useState } from 'react';
import '../../styles/warden-dashboard.css';

const WardenAgenticAlerts = () => {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showParentDetails, setShowParentDetails] = useState({});

  const fetchAlerts = async () => {
    setLoading(true);
    try {
      const response = await fetch('http://localhost:5000/api/warden/outpasses/alerts');
      const data = await response.json();
      setAlerts(Array.isArray(data.data) ? data.data : []);
    } catch (error) {
      console.error('Error fetching agentic AI alerts:', error);
      setAlerts([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
  }, []);

  const toggleParentDetails = (id) => {
    setShowParentDetails((previous) => ({ ...previous, [id]: !previous[id] }));
  };

  return (
    <div className="leave-page">
      <div className="leave-header">
        <h1>Agentic AI Alerts</h1>
        <p>View all overdue outpass alerts generated by autonomous monitoring.</p>
      </div>

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
        <div className="leave-meta">Total Alerts: {alerts.length}</div>
        <button className="action-btn primary" onClick={fetchAlerts} disabled={loading}>
          {loading ? 'Refreshing...' : 'Refresh Alerts'}
        </button>
      </div>

      {loading ? (
        <div className="leave-page"><p>Loading agentic AI alerts...</p></div>
      ) : alerts.length === 0 ? (
        <div className="leave-empty">
          <div className="leave-empty-card">
            <div className="leave-empty-icon" aria-hidden="true">📭</div>
            <h3>No active alerts found</h3>
            <p>No overdue alert notifications have been generated yet.</p>
          </div>
        </div>
      ) : (
        <div className="leave-list">
          <div
            style={{
              background: '#fef2f2',
              border: '1px solid #fca5a5',
              borderRadius: '8px',
              padding: '16px',
              marginBottom: '16px',
              color: '#991b1b'
            }}
          >
            <h3 style={{ margin: '0 0 8px 0', fontSize: '16px', fontWeight: '600' }}>🚨 Active Overdue Alerts</h3>
            <p style={{ margin: 0, fontSize: '14px' }}>
              These outpasses triggered automatic alerts. Student and parent notifications are shown below.
            </p>
          </div>

          {alerts.map((request) => {
            const parentDetailsVisible = showParentDetails[request.id];
            return (
              <article className="leave-card" key={request.id}>
                <div className="leave-card-top">
                  <div>
                    <div className="leave-name">{request.student_name || 'N/A'}</div>
                    <div className="leave-meta">
                      {request.roll_number || 'N/A'} · Room {request.room_number || 'N/A'}
                    </div>
                  </div>
                  <div className="leave-tags">
                    <span className={`tag ${request.status}`}>{request.status}</span>
                    {request.monitor_state && (
                      <span className={`tag ${request.monitor_state === 'overdue' ? 'rejected' : request.monitor_state === 'grace_period' ? 'pending' : 'approved'}`}>
                        {request.monitor_state.replace('_', ' ').toUpperCase()}
                      </span>
                    )}
                    {request.student_risk_level && (
                      <span className={`tag ${request.student_risk_level}`}>
                        Risk: {request.student_risk_level.toUpperCase()}
                      </span>
                    )}
                  </div>
                </div>

                <div className="leave-reason" style={{ background: '#fee2e2', borderColor: '#fca5a5' }}>
                  <div className="leave-label" style={{ color: '#991b1b' }}>🚨 Alert Generated</div>
                  <div className="leave-value" style={{ color: '#7f1d1d' }}>
                    {request.alert_to_student && '✅ Student email sent'}
                    {request.alert_to_student && request.alert_to_parent && ' · '}
                    {request.alert_to_parent && '✅ Parent email sent'}
                    {request.alert_sent_at && ` · Alert time: ${new Date(request.alert_sent_at).toLocaleString()}`}
                    {request.late_minutes && ` · Delay: ${request.late_minutes} minutes`}
                  </div>
                </div>

                <div className="leave-grid">
                  <div>
                    <div className="leave-label">Destination</div>
                    <div className="leave-value">{request.destination || 'N/A'}</div>
                  </div>
                  <div>
                    <div className="leave-label">Departure</div>
                    <div className="leave-value">{request.out_date || 'N/A'}</div>
                  </div>
                  <div>
                    <div className="leave-label">Expected Return</div>
                    <div className="leave-value">{request.expected_return_time || 'N/A'}</div>
                  </div>
                  <div>
                    <div className="leave-label">Alert Date</div>
                    <div className="leave-value">{request.alert_sent_at ? new Date(request.alert_sent_at).toLocaleDateString() : 'N/A'}</div>
                  </div>
                </div>

                {request.reason && (
                  <div className="leave-reason">
                    <div className="leave-label">Reason</div>
                    <div className="leave-value">{request.reason}</div>
                  </div>
                )}

                <div className="leave-reason">
                  <div className="leave-label">Parent/Guardian Information</div>
                  <button className="link-btn" type="button" onClick={() => toggleParentDetails(request.id)}>
                    {parentDetailsVisible ? 'Hide Parent Details' : 'Show Parent Details'}
                  </button>
                  {parentDetailsVisible && (
                    <div className="leave-value" style={{ marginTop: '8px' }}>
                      <div style={{ display: 'grid', gridTemplateColumns: 'auto 1fr', gap: '8px', padding: '12px', background: '#f9fafb', borderRadius: '6px' }}>
                        <strong>Parent Name:</strong>
                        <span>{request.parent_name || 'Not provided'}</span>
                        <strong>Parent Phone:</strong>
                        <span>{request.parent_phone || 'Not provided'}</span>
                        <strong>Parent Email:</strong>
                        <span>{request.parent_email || 'Not provided'}</span>
                        <strong>Emergency Contact:</strong>
                        <span>{request.emergency_contact || request.student_phone || 'Not provided'}</span>
                        <strong>Student Phone:</strong>
                        <span>{request.student_phone || 'Not provided'}</span>
                        <strong>Student Email:</strong>
                        <span>{request.student_email || 'Not provided'}</span>
                      </div>
                    </div>
                  )}
                </div>
              </article>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default WardenAgenticAlerts;

